# Generated by Django 4.2.7 on 2023-11-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_scope_options_alter_tag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='ArticleScope',
        ),
    ]
