# Generated by Django 4.2.7 on 2023-11-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articlescope_options_alter_tag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleScope',
            new_name='Scope',
        ),
    ]
